import {test,expect} from '@playwright/test';
test('shopper browser journey: account, search, color, cart persistence, coupon, COD checkout, order history',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/',{waitUntil:'domcontentloaded'});await expect(page.locator('#hero-section')).toBeVisible();
  await page.getByRole('button',{name:'Signup',exact:true}).click();
  await page.getByLabel('Name',{exact:true}).fill('Browser Customer');await page.getByLabel('Email',{exact:true}).fill(`browser-${Date.now()}@example.test`);await page.getByLabel('Password',{exact:true}).fill('browser-password-123');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByText('Welcome, Browser Customer')).toBeVisible();
  await page.locator('#search-trigger-button').click();await page.getByPlaceholder('Search essentials (e.g. oil sprayer, tumbler, mug)...').fill('1200ml');await page.locator('#search-modal-panel h4').first().click();
  await page.getByRole('button',{name:'Onyx Black',exact:true}).click();await page.locator('#modal-add-to-cart-btn').click();await expect(page.locator('#cart-drawer-panel')).toBeVisible();await expect(page.locator('#cart-drawer-panel')).toContainText('Onyx Black');
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('#cart-drawer-trigger').click();await expect(page.locator('#cart-drawer-panel')).toContainText('Onyx Black');await page.getByPlaceholder('Discount code (e.g. FAS10)').fill('FAS10');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByText('Coupon "FAS10" applied')).toBeVisible();
  await page.locator('#drawer-checkout-button').click();const checkout=page.locator('#checkout-modal-panel');const fields=checkout.locator('input');await fields.nth(1).fill('9876543210');await fields.nth(3).fill('123 Browser Test Street');await fields.nth(4).fill('Bengaluru');await fields.nth(5).fill('Karnataka');await fields.nth(6).fill('560038');await page.locator('#place-order-submit-button').click();await expect(page.getByText('Order Confirmed!',{exact:true})).toBeVisible();await expect(checkout).toContainText('₹539.10');await page.getByRole('button',{name:'Continue Shopping',exact:true}).click();await page.getByRole('button',{name:'My Orders',exact:true}).click();await expect(page.getByText('Ship to: 123 Browser Test Street',{exact:false})).toBeVisible();
  await expect(page.getByRole('link',{name:/Admin/i})).toHaveCount(0);await expect(page.getByRole('button',{name:/Admin/i})).toHaveCount(0);
  expect((await page.request.get('/admin')).status()).toBe(403);expect((await page.request.get('/api/admin/orders')).status()).toBe(403);
  await page.getByRole('button',{name:'Logout',exact:true}).click();await expect(page.getByRole('heading',{name:'Sign in',exact:true})).toBeVisible();expect((await page.request.get('/api/orders')).status()).toBe(401);
  expect(errors).toEqual([]);
});
test('admin browser manages inventory and products',async({page})=>{
 await page.goto('/admin',{waitUntil:'domcontentloaded'});await page.getByLabel('Email',{exact:true}).fill('admin@example.test');await page.getByLabel('Password',{exact:true}).fill('e2e-password-123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Store Administration'})).toBeVisible();await page.getByRole('button',{name:'Edit',exact:true}).first().click();await page.getByLabel('title',{exact:true}).fill('3-in-1 Soap Dispenser — Browser Verified');await page.getByLabel('stock',{exact:true}).first().fill('17');await page.getByRole('button',{name:'Save product',exact:true}).click();await expect(page.getByText('3-in-1 Soap Dispenser — Browser Verified',{exact:true})).toBeVisible();
});
test('mobile navigation, contact form and real empty reviews',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/',{waitUntil:'domcontentloaded'});await page.locator('#mobile-menu-trigger').click();await expect(page.locator('#mobile-navigation-drawer')).toContainText('Login');await expect(page.locator('#mobile-navigation-drawer')).toContainText('Signup');await expect(page.getByRole('link',{name:/Admin/i})).toHaveCount(0);await page.locator('#mobile-menu-trigger').click();const contact=page.locator('#contact-section');await contact.getByPlaceholder('e.g. Ananya Sen').fill('Test Shopper');await contact.getByPlaceholder('e.g. ananya@example.com').fill('test@example.test');await contact.getByPlaceholder('Describe how we can assist you...').fill('Please confirm the size of the steel tumbler.');await contact.getByRole('button',{name:'Send Message to Team'}).click();await expect(contact.getByText('Message Received')).toBeVisible();
});
