import React,{useState,useEffect} from 'react';
import {api} from '../lib/api';
import {useAuth} from '../context/AuthContext';
const button='px-3 py-2 rounded-xl bg-zinc-950 text-white text-xs font-bold disabled:opacity-50';
const input='w-full p-2 border border-zinc-300 rounded-lg bg-zinc-50';
const newProduct=()=>({id:crypto.randomUUID(),handle:'',title:'',categoryId:'',price:100,comparePrice:100,active:false,featured:false,details:{shortTitle:'',headline:'',description:'',features:[],specs:{material:''},careInstructions:[],highlights:[],images:[]},variants:[{id:crypto.randomUUID(),name:'Default',hex:'#18181B',stock:0,active:true}]});
export function Admin(){
  const {user}=useAuth(),[tab,setTab]=useState('products'),[rows,setRows]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[editor,setEditor]=useState<any>(null),[details,setDetails]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(){if(user?.role!=='admin')return;const [data,cats]=await Promise.all([api(`/admin/${tab}`),api('/categories')]);setRows(data);setCategories(cats);}
  useEffect(()=>{void load().catch(e=>setError(e.message));},[tab,user?.id]);
  async function action(f:()=>Promise<unknown>){setBusy(true);setError('');try{await f();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function edit(p:any){setEditor(structuredClone(p));setDetails(JSON.stringify(p.details,null,2));}
  if(user?.role!=='admin')return <section className="p-10">Administrator access required. <a href="#account" className="underline">Sign in</a></section>;
  return <section className="max-w-6xl mx-auto p-6 space-y-6"><h1 className="font-display text-3xl font-bold">Store Administration</h1><div className="flex flex-wrap gap-2">{['products','orders','users','messages'].map(t=><button key={t} className={button} onClick={()=>{setTab(t);setEditor(null);}}>{t}</button>)}<button className={button} disabled={busy} onClick={()=>action(load)}>Refresh</button></div>{error&&<p role="alert" className="text-red-700 bg-red-50 p-3 rounded-xl">{error}</p>}
    {tab==='products'&&<><div className="flex gap-3"><button className={button} onClick={()=>edit(newProduct())}>Add product</button></div><form className="flex gap-2 max-w-md" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(()=>api('/admin/categories','POST',{name:f.get('name')}));}}><input className={input} name="name" required placeholder="New category name"/><button className={button} disabled={busy}>Add category</button></form>
      <details className="border rounded-xl p-3"><summary>Manage categories</summary>{categories.map(c=><form className="flex gap-2 my-2" key={c.id} onSubmit={e=>{e.preventDefault();void action(()=>api(`/admin/categories/${c.id}`,'PATCH',{name:new FormData(e.currentTarget).get('name')}));}}><input className={input} name="name" defaultValue={c.name} required/><button className={button} disabled={busy}>Rename</button></form>)}</details>
      {editor?<form className="bg-white border rounded-2xl p-5 space-y-4" onSubmit={e=>{e.preventDefault();void action(async()=>{await api(`/admin/products/${editor.id}`,'PUT',{...editor,details:JSON.parse(details)});setEditor(null);});}}><h2 className="font-bold">Product editor</h2><p className="text-xs">Amounts are in paise (₹1 = 100 paise). Stock means units available to sell, excluding existing orders.</p><div className="grid sm:grid-cols-2 gap-3">{['title','handle','price','comparePrice'].map(key=><label key={key}>{key}<input required className={input} type={key.includes('rice')?'number':'text'} min={1} value={editor[key]} onChange={e=>setEditor({...editor,[key]:key.includes('rice')?Number(e.target.value):e.target.value})}/></label>)}<label>Category<select required className={input} value={editor.categoryId} onChange={e=>setEditor({...editor,categoryId:e.target.value})}><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="flex gap-5">{['active','featured'].map(k=><label key={k}><input type="checkbox" checked={editor[k]} onChange={e=>setEditor({...editor,[k]:e.target.checked})}/> {k}</label>)}</div>
      <label className="block">Description, features, specifications and HTTPS image URLs (JSON)<textarea className={`${input} font-mono text-xs`} rows={16} value={details} onChange={e=>setDetails(e.target.value)}/></label><h3 className="font-bold">Color variants and inventory</h3>{editor.variants.map((v:any,i:number)=><div key={v.id} className="grid grid-cols-2 sm:grid-cols-4 gap-2">{['name','hex','stock'].map(k=><label key={k}>{k}<input className={input} type={k==='stock'?'number':k==='hex'?'color':'text'} min={0} value={v[k]} onChange={e=>{const vs=[...editor.variants];vs[i]={...v,[k]:k==='stock'?Number(e.target.value):e.target.value};setEditor({...editor,variants:vs});}}/></label>)}<label className="self-end pb-2"><input type="checkbox" checked={v.active} onChange={e=>{const vs=[...editor.variants];vs[i]={...v,active:e.target.checked};setEditor({...editor,variants:vs});}}/> Available</label></div>)}<button type="button" className={button} onClick={()=>setEditor({...editor,variants:[...editor.variants,{id:crypto.randomUUID(),name:'New color',hex:'#18181B',stock:0,active:true}]})}>Add variant</button><div className="flex gap-3"><button disabled={busy} className={button}>Save product</button><button type="button" className={button} onClick={()=>setEditor(null)}>Close editor</button></div></form>:rows.map(p=><div key={p.id} className="border bg-white rounded-xl p-4 flex justify-between gap-4"><span><span>{p.title}</span><small className="block">{p.active?'Active':'Inactive'} · ₹{p.price/100} · {p.variants.reduce((n:number,v:any)=>n+v.stock,0)} available</small></span><div className="flex gap-2"><button className={button} onClick={()=>edit(p)}>Edit</button><button className={button} disabled={busy} onClick={()=>action(()=>api(`/admin/products/${p.id}`,'DELETE'))}>Archive</button></div></div>)}</>}
    {tab==='orders'&&rows.map(o=><article key={o.id} className="border bg-white rounded-2xl p-5 space-y-3"><h2 className="font-bold break-all">{o.id} · ₹{o.total/100}</h2><p>{o.status} · {o.payment_method} · {o.payment_status}</p><p className="text-sm">{o.address.fullName}, {o.address.email}, {o.address.phone}<br/>{o.address.address}, {o.address.city}, {o.address.state} {o.address.postalCode}</p><p>{o.note}</p>{o.items.map((i:any)=><p key={i.id} className="text-xs">{i.title} — {i.color} × {i.quantity}</p>)}<form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(()=>api(`/admin/orders/${o.id}`,'PATCH',{status:f.get('status'),trackingUrl:f.get('trackingUrl')}));}}><select name="status" className="border rounded-lg p-2"><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered / COD collected</option><option value="cancelled">Cancel unpaid</option></select><input name="trackingUrl" defaultValue={o.tracking_url} placeholder="HTTPS tracking URL" className="border rounded-lg p-2"/><button className={button} disabled={busy}>Update order</button></form>{o.payment_id&&o.payment_status==='paid'&&!['shipped','delivered'].includes(o.status)&&<button className={button} disabled={busy} onClick={()=>{if(window.confirm('Issue a full refund to the original payment method?'))void action(()=>api(`/admin/orders/${o.id}/refund`,'POST'));}}>Refund ₹{o.total/100}</button>}{o.payment_method==='upi'&&<form className="flex gap-2" onSubmit={e=>{e.preventDefault();const providerOrderId=new FormData(e.currentTarget).get('providerOrderId');void action(()=>api(`/admin/orders/${o.id}/reconcile`,'POST',providerOrderId?{providerOrderId}:{}));}}>{!o.provider_order_id&&<input className="border rounded-lg p-2" name="providerOrderId" placeholder="Razorpay order ID from dashboard" required/>}<button className={button} disabled={busy}>Reconcile payment / refund</button></form>}{['payment_initialization_failed','refund_pending','payment_review'].includes(o.status)&&<p className="text-amber-800 text-sm">Requires payment reconciliation. Check the provider dashboard and the README recovery procedure.</p>}</article>)}
    {tab==='users'&&rows.map(u=><form key={u.id} className="border bg-white rounded-xl p-4 flex flex-wrap gap-3 items-center" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(()=>api(`/admin/users/${u.id}`,'PATCH',{role:f.get('role'),active:f.get('active')==='on'}));}}><span className="flex-1">{u.name} · {u.email}</span><select name="role" defaultValue={u.role}><option>customer</option><option>admin</option></select><label><input type="checkbox" name="active" defaultChecked={!!u.active}/> Active</label><button disabled={busy||u.id===user.id} className={button}>Save access</button></form>)}
    {tab==='messages'&&rows.map(m=><article key={m.id} className="bg-white border rounded-xl p-4 space-y-2"><strong>{m.name} · {m.email} · {m.phone}</strong><p className="whitespace-pre-wrap">{m.comment}</p><button className={button} disabled={busy} onClick={()=>action(()=>api(`/admin/messages/${m.id}`,'PATCH',{status:m.status==='open'?'resolved':'open'}))}>{m.status==='open'?'Mark resolved':'Reopen'}</button></article>)}
    {!rows.length&&!editor&&<p>No records to display.</p>}
  </section>;
}
